server:
  port: 8080

spring:
  main:
    banner-mode: off
  jpa:
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    generate-ddl: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: create
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://database:5432/book-store
    username: postgres
    password: postgres321
  sql:
    init:
      mode: always